[book]
authors = ["Felix Touchte Codjo"]
language = "en"
multilingual = false
src = "src"
title = "ALERT Software documentation"


[output.html]
mathjax-support = true

[output.html.code.hidelines]
json = "~"